# vim:fileencoding=utf-8:foldmethod=marker


# : App {{{

[app]
overall = { bg = "#1a1b26" }

# : }}}


# : Manager {{{

[mgr]
cwd = { fg = "#7aa2f7" }

# Find
find_keyword = { fg = "#f7768e", bold = true, italic = true, underline = true }
find_position = { fg = "#bb9af7", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "#9ece6a", bg = "#9ece6a" }
marker_cut = { fg = "#e0af68", bg = "#f7768e" }
marker_marked = { fg = "#7aa2f7", bg = "#7dcfff" }
marker_selected = { fg = "#e0af68", bg = "#e0af68" }

# Count
count_copied = { fg = "#1a1b26", bg = "#9ece6a" }
count_cut = { fg = "#1a1b26", bg = "#e0af68" }
count_selected = { fg = "#1a1b26", bg = "#7aa2f7" }

# Border
border_symbol = "│"
border_style = { fg = "#414868" }

# : }}}


# : Indicator {{{

[indicator]
parent = { reversed = true }
current = { reversed = true }
preview = { underline = true }

# : }}}


# : Tabs {{{

[tabs]
active = { fg = "#292e42", bg = "#7aa2f7", bold = true }
inactive = { fg = "#7aa2f7", bg = "#292e42" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#292e42", bg = "#7aa2f7", bold = true }
normal_alt = { fg = "#7aa2f7", bg = "#292e42" }

# Select mode
select_main = { fg = "#292e42", bg = "#9ece6a", bold = true }
select_alt = { fg = "#7aa2f7", bg = "#292e42" }

# Unset mode
unset_main = { fg = "#292e42", bg = "#bb9af7", bold = true }
unset_alt = { fg = "#7aa2f7", bg = "#292e42" }

# : }}}


# : Status bar {{{

[status]
overall = { fg = "#7aa2f7" }
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { fg = "#292e42", bold = true }
progress_normal = { fg = "#7aa2f7", bg = "#292e42" }
progress_error = { fg = "#f7768e", bg = "#292e42" }

# Permissions
perm_sep = { fg = "#7aa2f7" }
perm_type = { fg = "#9ece6a" }
perm_read = { fg = "#e0af68" }
perm_write = { fg = "#f7768e" }
perm_exec = { fg = "#bb9af7" }


# : }}}


# : Which {{{

[which]
mask = { bg = "#16161e" }
cand = { fg = "#9ece6a" }
rest = { fg = "#a9b1d6" }
desc = { fg = "#bb9af7" }
separator = "  "
separator_style = { fg = "#414868" }

# : }}}


# : Confirm {{{

[confirm]
border = { fg = "#7aa2f7" }
title = { fg = "#7aa2f7" }
body = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#7aa2f7" }
title = { fg = "#7aa2f7" }
tbl_col = { fg = "#9ece6a" }
tbl_cell = { fg = "#bb9af7", bg = "#292e42" }

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "#9ece6a" }
title_warn = { fg = "#f7768e" }
title_error = { fg = "#e0af68" }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#7aa2f7" }
active = { fg = "#bb9af7", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#7aa2f7" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#7aa2f7" }
active = {}
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#7aa2f7" }
title = {}
hovered = { fg = "#bb9af7", underline = true }

# : }}}


# : Help {{{

[help]
on = { fg = "#9ece6a" }
run = { fg = "#bb9af7" }
desc = { fg = "#c0caf5" }
hovered = { reversed = true, bold = true }
footer = { fg = "#1a1b26", bg = "#a9b1d6" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#e0af68" },

  # Media
  { mime = "{audio,video}/*", fg = "#f7768e" },

  # Archives
  { mime = "application/zip", fg = "#bb9af7" },
  { mime = "application/x-{tar,bzip*,bzip2,7z-compressed,rar,xz}", fg = "#bb9af7" },

  # Documents
  { mime = "application/{doc,epub*,pdf,rtf,vnd.*}", fg = "#9ece6a" },

  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "#5d6173" },

  # Special files
  { mime = "*", is = "orphan", fg = "#f29cb4", bg = "#93000a" },
  { mime = "application/*exec*", fg = "#f7768e" },

  # Fallback
  { url = "*", fg = "#c6d0f5" },
  { url = "*/", fg = "#7aa2f7" },
]

# : }}}


# : Icons {{{

[icon]
prepend_dirs = [
  { name = "Desktop", text = "󰍹", fg = "#7aa2f7" },
  { name = "Documents", text = "󱉟", fg = "#7aa2f7" },
  { name = "Books", text = "", fg = "#7aa2f7" },
  { name = "Study", text = "󰗚", fg = "#7aa2f7" },
  { name = "Downloads", text = "", fg = "#7aa2f7" },
  { name = "Games", text = "", fg = "#7aa2f7" },
  { name = "Music", text = "", fg = "#7aa2f7" },
  { name = "Pictures", text = "", fg = "#7aa2f7" },
  { name = "Photos", text = "", fg = "#7aa2f7" },
  { name = "Screenshots", text = "󰹑", fg = "#7aa2f7" },
  { name = "Wallpapers", text = "󰸉", fg = "#7aa2f7" },
  { name = "Programming", text = "󰘦", fg = "#7aa2f7" },
  { name = "Code", text = "", fg = "#7aa2f7" },
  { name = "Public", text = "󰀑", fg = "#7aa2f7" },
  { name = "Source", text = "󰘬", fg = "#7aa2f7" },
  { name = "Shares", text = "", fg = "#7aa2f7" },
  { name = "Templates", text = "", fg = "#7aa2f7" },
  { name = "Utility", text = "", fg = "#7aa2f7" },
  { name = "Tools", text = "", fg = "#7aa2f7" },
  { name = "Vault", text = "", fg = "#7aa2f7" },
  { name = "Videos", text = "", fg = "#7aa2f7" },
  { name = "Workspaces", text = "󰍺", fg = "#7aa2f7" },
  { name = "Dashboard", text = "", fg = "#7aa2f7" },
  { name = "Cloud", text = "󰅟", fg = "#7aa2f7" },
]

prepend_conds = [{ if = "dir", text = "", fg = "#7aa2f7" }]

# : }}}
